export const HELP_TEXT = [
  'GetThreads Bot',
  '',
  '傳送連結即可自動儲存內容與評論：',
  'X / Threads / Reddit / YouTube / GitHub',
  '微博 / B站 / 小紅書 / 抖音 / 任何網頁',
  '',
  '指令：',
  '/search <查詢> — 網頁搜尋',
  '/monitor <關鍵字> — 跨平台搜尋提及',
  '/timeline @用戶 — 抓取用戶最近貼文',
  '/ask <問題> — 用知識庫回答問題',
  '/knowledge — 知識庫總覽（缺口/技能/偏好/分析）',
  '/explore <主題> — 知識探索（推薦/簡報/對比）',
  '/digest — 知識報告（精華/蒸餾/整合）',
  '/discover <關鍵字> — GitHub 專案探索（無參數=熱門）',
  '/learn — Vault 學習（分類規則/重新分類/翻譯）',
  '/reprocess <路徑> — 重新 AI 豐富筆記',
  '/reformat --dry-run — 掃描排版問題（--all 修復、--llm 加強）',
  '/dedup — 掃描並清理重複筆記（--fix 執行刪除）',
  '/retry — 重試失敗的連結',
  '/subscribe @用戶 — 訂閱自動追蹤',
  '/quality — Vault 品質報告',
  '/suggest — 相關筆記推薦（自動連結）',
  '/radar — 內容雷達（自動搜尋+存入）',
  '/radar wall — AI 工具情報牆（活躍/沉寂/匹配）',
  '/benchmark — 品質基準報告（評分趨勢/平台成功率）',
  '/status — Bot 狀態與本次儲存',
  '/health — 系統健康報告（記憶體/Extractor/Vault）',
  '/doctor — 全面即時診斷（探測所有平台+工具檢查）',
  '/logs [n] [error] — 查看最近 log',
  '/restart — 遠端重啟 Bot',
  '/clear — 清除處理佇列',
  '/help — 顯示此說明',
].join('\n');

export const BOT_COMMANDS_MENU = [
  { command: 'start', description: '顯示 Bot 說明' },
  { command: 'search', description: '網頁搜尋' },
  { command: 'monitor', description: '跨平台搜尋提及' },
  { command: 'timeline', description: '抓取用戶最近貼文' },
  { command: 'ask', description: '用知識庫回答問題' },
  { command: 'knowledge', description: '知識庫總覽' },
  { command: 'explore', description: '知識探索（推薦/簡報/對比）' },
  { command: 'digest', description: '知識報告' },
  { command: 'discover', description: 'GitHub 專案探索' },
  { command: 'learn', description: 'Vault 學習與分類' },
  { command: 'reprocess', description: '重新 AI 豐富筆記' },
  { command: 'reformat', description: '修復筆記排版' },
  { command: 'dedup', description: '掃描並清理重複筆記' },
  { command: 'retry', description: '重試失敗的連結' },
  { command: 'subscribe', description: '訂閱自動追蹤' },
  { command: 'quality', description: 'Vault 品質報告' },
  { command: 'suggest', description: '相關筆記推薦' },
  { command: 'radar', description: '內容雷達' },
  { command: 'benchmark', description: '品質基準報告' },
  { command: 'status', description: 'Bot 狀態' },
  { command: 'health', description: '系統健康報告' },
  { command: 'doctor', description: '全面即時診斷' },
  { command: 'logs', description: '查看最近 log' },
  { command: 'restart', description: '遠端重啟 Bot' },
  { command: 'clear', description: '清除處理佇列' },
  { command: 'help', description: '顯示說明' },
];
