export const HELP_TEXT = [
  'ObsBot — 傳送連結即可自動儲存',
  'X / Threads / Reddit / YouTube / GitHub',
  '微博 / B站 / 小紅書 / 抖音 / 任何網頁',
  '',
  '常用指令：',
  '/find <關鍵字> — 搜尋 Vault 筆記',
  '/search <查詢> — 網頁搜尋',
  '/ask <問題> — 用知識庫回答問題',
  '/explore <主題> — 知識探索',
  '/discover <關鍵字> — GitHub 專案探索',
  '/digest weekly — 週報深度合成',
  '/radar — 內容雷達（自動搜尋+存入）',
  '/status — Bot 狀態',
  '/help all — 顯示所有指令',
].join('\n');

export const HELP_ALL_TEXT = [
  'ObsBot 完整指令列表',
  '',
  '📥 內容收集',
  '/find <關鍵字> — 搜尋 Vault 筆記（frontmatter + 全文）',
  '/search <查詢> — 網頁搜尋',
  '/monitor <關鍵字> — 跨平台搜尋提及',
  '/timeline @用戶 — 抓取用戶最近貼文',
  '/subscribe @用戶 — 訂閱自動追蹤（目前支援 Threads）',
  '/radar — 內容雷達（自動搜尋+存入）',
  '/radar wall — AI 工具情報牆',
  '/patrol — 多平台內容巡邏（GitHub/HN/Reddit/DevTo）',
  '/discover <關鍵字> — GitHub 專案探索',
  '/vsearch <關鍵字> — 搜尋影片筆記（章節/轉錄）',
  '',
  '🧠 知識系統',
  '/ask <問題> — 用知識庫回答問題',
  '/knowledge [gaps|skills|analyze] — 知識庫總覽',
  '/explore <主題> — 知識探索（推薦/簡報/深度合成）',
  '/explore <A> vs <B> — 主題對比分析',
  '/digest [weekly|distill] — 知識報告（精華/週報/蒸餾/整合）',
  '/suggest — 相關筆記推薦（自動連結）',
  '/learn — Vault 學習（分類規則/重新分類/翻譯）',
  '',
  '🔧 Vault 維護',
  '/reprocess <路徑> — 重新 AI 豐富筆記',
  '/reformat --dry-run — 掃描排版問題（--all 修復）',
  '/dedup — 掃描重複筆記（按鈕確認刪除）',
  '/quality — Vault 品質報告',
  '/benchmark — 品質基準報告（評分趨勢/平台成功率）',
  '/retry — 重試失敗的連結',
  '',
  '⚙️ 系統管理',
  '/status — Bot 狀態與本次儲存',
  '/health — 系統健康報告',
  '/doctor — 全面即時診斷（探測所有平台+工具）',
  '/logs [n] [error] — 查看最近 log',
  '/restart — 遠端重啟 Bot（需確認）',
  '/code <action> — 遠端執行指令（health/status/test/log）',
  '/clear — 清除處理佇列',
].join('\n');

/** Top-priority commands for Telegram menu (max ~30 recommended) */
export const BOT_COMMANDS_MENU = [
  // Content collection
  { command: 'find', description: '搜尋 Vault 筆記' },
  { command: 'search', description: '網頁搜尋' },
  { command: 'monitor', description: '跨平台搜尋提及' },
  { command: 'timeline', description: '抓取用戶最近貼文' },
  { command: 'subscribe', description: '訂閱自動追蹤（Threads）' },
  { command: 'radar', description: '內容雷達' },
  { command: 'patrol', description: '多平台內容巡邏' },
  { command: 'discover', description: 'GitHub 專案探索' },
  { command: 'vsearch', description: '搜尋影片筆記' },
  // Knowledge
  { command: 'ask', description: '用知識庫回答問題' },
  { command: 'knowledge', description: '知識庫總覽' },
  { command: 'explore', description: '知識探索（推薦/簡報/深度合成）' },
  { command: 'digest', description: '知識報告（精華/週報/蒸餾）' },
  { command: 'suggest', description: '相關筆記推薦' },
  { command: 'learn', description: 'Vault 學習與分類' },
  // Vault maintenance
  { command: 'reprocess', description: '重新 AI 豐富筆記' },
  { command: 'reformat', description: '修復筆記排版' },
  { command: 'dedup', description: '掃描重複筆記' },
  { command: 'quality', description: 'Vault 品質報告' },
  { command: 'benchmark', description: '品質基準報告' },
  { command: 'retry', description: '重試失敗的連結' },
  // System
  { command: 'status', description: 'Bot 狀態' },
  { command: 'health', description: '系統健康報告' },
  { command: 'doctor', description: '全面即時診斷' },
  { command: 'logs', description: '查看最近 log' },
  { command: 'restart', description: '遠端重啟 Bot' },
  { command: 'code', description: '遠端執行指令' },
  { command: 'clear', description: '清除處理佇列' },
  { command: 'help', description: '顯示說明' },
];
